### ISSUE TITLE
autoplot type 'cd' error to warning?

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3benchmark#21]
Sometimes I want to show the CD Diagram and plot it even if there are no significant differences (to show that this is the case).
Could we consider raising a warning instead of an error? Or alternatively, should we provide an option that allows to disable this check?

**Comment by RaphaelS1** [comment]
> Sometimes I want to show the CD Diagram and plot it even if there are no significant differences (to show that this is the case).

What do you gain from visualising a non-significant plot? CD plot is already too complicated for many people, I worry this will lead to easy misuse. 

> Or alternatively, should we provide an option that allows to disable this check?

This is actually already possible but it's a hidden feature. Just set `p.value = 1`

**Comment by berndbischl** [comment]
i dunno errors are always not so great here. just doc the hidden feature?

**Comment by RaphaelS1** [comment]
https://github.com/mlr-org/mlr3benchmark/blob/74a4cfeb69bf4a208e2f00a72dbeb890d7f7a440/R/autoplot.BenchmarkAggr.R#L27-L28

**Comment by pfistfl** [comment]
It’s a different thing to do p value = 1 and getting non-significant CDs

**Comment by RaphaelS1** [comment]
Ah true because the critical differences change. Do you want to do PR a fix? Just needs an arg to switch this off https://github.com/mlr-org/mlr3benchmark/blob/main/R/BenchmarkAggr.R#L326

**Comment by RaphaelS1** [comment]
Closed in #22
